#!/bin/bash

ERROR=0
WARN=1
INFO=2
DEBUG=3

LOG_LEVEL=${LOG_LEVEL:-$INFO}

log() {
    local log_level_int=$1

    if [[ $log_level_int -gt $LOG_LEVEL ]]; then
        return
    fi

    local log_level_str=""

    case $log_level_int in
        $ERROR)
            # Red
            color="31"
            log_level_str="ERROR"
            ;;
        $WARN)
            # Yellow
            color="33"
            log_level_str="WARN"
            ;;
        $DEBUG)
            # Cyan
            color="36"
            log_level_str="DEBUG"
            ;;
        $INFO)
            # Green
            color="32"
            log_level_str="INFO"
            ;;
        *)
            # Use default color for unrecognized log level
            color="38"
            ;;
    esac

    local message=${@:3}
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
    local log_message="[$timestamp][$log_level_str] $message"
    echo -e "\033[1;${color}m${log_message}\033[0m"
}

error() {
    log $ERROR $@
}

warn() {
    log $WARN $@
}

info() {
    log $INFO $@
}

debug() {
    log $DEBUG $@
}