#!/bin/sh
/bin/busybox --install -s /bin/

mount -t proc proc /proc
mount -t sysfs sysfs /sys
#echo "/sbin/mdev" > /proc/sys/kernel/hotplug
#echo "hello linux"

modprobe -a vhost_vsock vmw_vsock_virtio_transport

find /sys/ -name modalias -print0 | \
    xargs -0 sort -u | \
    tr '\n' '\0' | \
    xargs -0 modprobe -abq

mdev -s
mkdir /dev/pts
mount -t devpts devpts /dev/pts
exec /bin/busybox init