#!/bin/sh
/usr/bin/busybox --install -s /usr/bin/

mount -t tmpfs tmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug 
mdev -s

/usr/bin/modprobe -a vhost_vsock vmw_vsock_virtio_transport

find /sys/ -name modalias -print0 | \
    xargs -0 sort -u | \
    tr '\n' '\0' | \
    xargs -0 /usr/bin/modprobe -abq

acpid

socat vsock-listen:4321,reuseaddr,fork "exec:'xargs --no-run-if-empty -0 sh -c',stderr" &