#!/bin/bash

in="$1"
if [ -z "${in}" ]; then
    exit 1
fi

ikm="$2"
if [ -z "${ikm}" ]; then
    exit 1
fi

# Extract 16-byte IV, 32-byte wrapping key and 32-byte hmac key from IKM
iv="${ikm:0:32}"
wrap_key="${ikm:32:64}"
hmac_key="${ikm:96:64}"

# Print salt, IV and key
echo -ne "${in}" | xxd -p -r | openssl enc \
  -e -aes-256-cbc -nosalt -P \
  -iv "${iv}" \
  -K "${wrap_key}" >&2

# Encrypt passphrase
enc_data="$(echo -ne "${in}" | xxd -p -r | openssl enc \
  -e -aes-256-cbc -nosalt \
  -iv "${iv}" \
  -K "${wrap_key}" | xxd -p | tr -d "\n")"
len="$(echo -ne "${enc_data}" | wc -c)"
len="$(printf "%08X\n" "$((len / 2))")"

# Calculate authentication tag
tag="$(echo -ne "${enc_data}" | xxd -p -r | openssl dgst \
  -sha256 -binary \
  -hmac "${hmac_key}" | xxd -p | tr -d "\n")"

echo -n "ENCP${len}${enc_data}${tag}"