#!/bin/sh

PATH=$PATH:/usr/local/bin:/usr/local/libexec/shelter

BUSYBOX="/usr/bin/busybox"
[ ! -x "$BUSYBOX" ] && BUSYBOX="/usr/sbin/busybox"

$BUSYBOX --install -s /usr/bin/

mount -t tmpfs tmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -t devpts devpts /dev/pts

/usr/bin/modprobe -a virtio virtio_blk virtio_pci virtio_net dm_crypt vhost_vsock vmw_vsock_virtio_transport

find /sys/ -name modalias -print0 | \
    xargs -0 sort -u | \
    tr '\n' '\0' | \
    xargs -0 /usr/bin/modprobe -abq

if [ -e /proc/sys/kernel/hotplug ]; then
    echo `which mdev` > /proc/sys/kernel/hotplug
fi
mdev -d || mdev -s

# try to config network
ip link set eth0 up
udhcpc -s /usr/share/udhcpc/default.script

kbs-client --url $KBS_URL get-resource --path $PASSPHRASE_PATH | base64 -d | cryptsetup open -d - /dev/vda1 root

if [ $? -ne 0 ]; then
    echo "luks2 open failed!!"
    exec init
fi

mount -t ext4 /dev/mapper/root /mnt

mount -o move /sys /mnt/sys
mount -o move /proc /mnt/proc
mount -o move /dev /mnt/dev

exec switch_root /mnt /init