#!/bin/sh

BUSYBOX="/usr/bin/busybox"
[ ! -x "$BUSYBOX" ] && BUSYBOX="/usr/sbin/busybox"

$BUSYBOX --install -s /usr/bin/

acpid

socat -t 3600 vsock-listen:4321,reuseaddr,fork "exec:'xargs --no-run-if-empty -0 sh -c',stderr" &

# try to config network
iplink set eth0 up
udhcpc -b

# start the other service
for script in $(find /etc/init.d -maxdepth 1 -type f -perm /111 ! -name rcS); do
    $script start
done
