#!/bin/sh

BUSYBOX="/usr/bin/busybox"
[ ! -x "$BUSYBOX" ] && BUSYBOX="/usr/sbin/busybox"

$BUSYBOX --install -s /usr/bin/

acpid

socat -t 3600 vsock-listen:4321,reuseaddr,fork "exec:'xargs --no-run-if-empty -0 sh -c',stderr" &
