#!/bin/sh

PATH=$PATH:/usr/local/bin:/usr/local/libexec/shelter

BUSYBOX="/usr/bin/busybox"
[ ! -x "$BUSYBOX" ] && BUSYBOX="/usr/sbin/busybox"

$BUSYBOX --install -s /usr/bin/

mount -t tmpfs tmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -t devpts devpts /dev/pts

if [ -e /proc/sys/kernel/hotplug ]; then
    echo `which mdev` > /proc/sys/kernel/hotplug
fi
mdev -d || mdev -s

/usr/bin/modprobe -a vhost_vsock vmw_vsock_virtio_transport

find /sys/ -name modalias -print0 | \
    xargs -0 sort -u | \
    tr '\n' '\0' | \
    xargs -0 /usr/bin/modprobe -abq

acpid

# try to config network
ip link set eth0 up
udhcpc -s /usr/share/udhcpc/default.script

kbs-client --url $KBS_URL attest || poweroff

socat -t 3600 vsock-listen:4321,reuseaddr,fork "exec:'xargs --no-run-if-empty -0 sh -c',stderr" &

# start the other service
for script in $(find /etc/init.d -maxdepth 1 -type f -perm /111 ! -name rcS); do
    $script start
done
